### ISSUE TITLE
Handle arguments

### ISSUE THREAD

**Issue by GaryBoone** [codeitlikemiley/cargo-runner#5]
While cmd-R is convenient, sometimes we need to start our runs with arguments, like:

$ cargo run -- --num_agents=5 --use_submarine_base

Suggestions:

1. Clarify the documentation to explain how arguments are handled by `cargo-runner`.
2. Add a mechanism, if not present, to allow adding and changing arguments.

Naturally, we wouldn't want to interfere with the convenience of the simple cmd-R command. So maybe shift-cmd-R brings up a dialog box for parameters? Or `cargo-runner` would look for a default file like `.cargo-runner-args` and append its contents, if present? Either way, it should default to the last used arguments.

**Comment by codeitlikemiley** [comment]
As of the moment there is no way to pass custom arguments 
but if you wish to change the default cargo run command
the default command is always

```sh
cargo run --package package_name --bin bin_name
```

which are from your cargo.toml 

but if you need to always run the same cargo run with same arguments
you might want to use a Makefile

e.g.
`Makefile` - can be define per crate
```Makefile
# Default target
.PHONY: all
all: build

# Build target
.PHONY: build
build:
	cargo build --package PKG_NAME

.PHONY: run
run:
	cargo run --package PKG_NAME --bin BIN_NAME -- --num_agents=5 --use_submarine_base

# Test target
.PHONY: test
test:
	cargo test

# Clean up
.PHONY: clean
clean:
	cargo clean
```

If that would solve your current problem , then Makefile i think would suffice

if you really wanna run any cargo commands you might want to check [cargo-bin](https://github.com/codeitlikemiley/cargo-bin) which would allow you to run any cargo commands

with that said, i understand there is a usecase for your suggestion
I might be able to add your request by making a cargo-runner.toml file
and an extra keybind like you mentioned or a command available at command palette.

What I had in mind is  
lets say I added the  command ` cargo runner override`
you would get prompted what you wanna override
e.g.

options:
- run
- build
- test
- single file rust script
- bench

then you will be asked what parameters you wanna pass in

example :

num_agents:String
use_submarine_base:bool

then that would generate something like

```toml
package_name = "pkg"

[[bin]]
name = "pkg"
path = "path/to/bin/bin_or_main.rs"

[[parameters.run]]
name = "num_agents"
type = "String"
default = "6"

[[parameters.run]]
name = "use_submarine_base"
type = "bool"
default = true
```

then if we press lets say CMD+SHIFT+R

it would show what command it would run
would you like to run `cargo run --package pkg --bin pkg -- --num_agents=6 --use_submarine_base`
if you press enter then it would run that, if you type No , NO or n and press enter 
you will be asked first for num_agents
then will be asked for use_submarine_base

then it would run that command and would update the `cargo-runner.toml `

let me know if this is the behavior you want 

If we go down this path then i might need to remove support  of Makefile 


@GaryBoone  let me know what you think about this idea

**Comment by GaryBoone** [comment]
Yes, the common use case I see is being able to quickly add command line parameters, run the new command line repeatedly with those parameters, then make some changes to the parameters, then repeat with those. Maybe drop them when I'm done and change tasks, or set some common ones used throughout development. So the key requirement I think is keeping this feature consistent with the strength of `cargo-runner`: no-click and fast.

The workflow suggested above is excellent. 
1) The first time you use `cargo runner override`, you're prompted for the required input.
2) The info is reused on subsequent runs so it's fast on repeat uses.
3) There's an easy way to edit the parameters on repeat uses.
4) You now have two ways to run fast: CMD-R runs without parameters. CMD+SHIFT+R runs with the current overrides. [Love this: it's fast and flexible. It also prevents confusion of what will be run because they're two separate commands.]

The description sounded like some of the prompts are sequential. Could there be a single dialog box for everything? Eg, it's just a list of overrides, where an override says what to override, and then lists the arguments with `+` for `add parameter` and a pencil icon for `edit parameter`?

BTW, as an initial version, could we just add all of the parameters as a simple string? That would be simpler from a UI as well as coding perspective.

In addition, I'm not sure we want strong typing for command line arguments, for these reasons:
1) They aren't typed on the command line. They're just a string, or perhaps a vec of strings.
2) It's extra work to type them in the `cargo-runner` UI.
3) It's the responsibility of the user's code to convert the command line string arguments to validated, typed, arguments.
4) It means that the user has to synchronize the types in two places: their code and the `cargo-runner` UI.
5) It could mask bugs if my code doesn't correctly convert the arguments, but I never know about it because `cargo-runner` always ensures the right type for me.

**Comment by codeitlikemiley** [comment]
@GaryBoone  , been very busy , but now you can add overriding parameters

please check this for instruction on how to use this feature

https://github.com/codeitlikemiley/cargo-runner/pull/11
